---
- hosts: all
  vars_files:
    - vcenter_vars.yml
    
  vars:
    test_nets:
      - name: "VM-test-net-1"
      - device_type: vmxnet3
    #  - name: "VM-test-net-2" 
  
  tasks:
  
    - debug:
        msg: "{{ nic_list.0 }}"
      
    - name: VMWARE_GUEST | connect vNICs to correct network
      connection: local
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username:  "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ vm_name }}"
        folder: "{{ folder }}"
        datacenter: "{{ datacenter_2 }}"
        cluster: "{{ cluster_2 }}"
        validate_certs: false
        state: present
        networks:
        - name: "VM-Private"
          device_type: vmxnet3
        - name: "{{ test_nets }}"
     #   - name: "{{ nic_list.0 }}"
     #   - name: "{{ nic_list.1 }}"
   #   with_items: "{{ nic_list }}"
        #  device_type: vmxnet3
       #   with_items:
       #     - VM-test-net-1
       #     - VM-test-net-2
      #  - name: "{{ nic2_network }}"
      #    device_type:  vmxnet3
       
      register: vm_net_reconfigured
