---
- hosts: all
  vars_files:
    - vcenter_vars.yml
  
  tasks:
      
    - name: VMWARE_GUEST | connect vNICs to correct network
      connection: local
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username:  "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
        folder: "{{ vm_folder }}"
        datacenter: "{{ esxi_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        validate_certs: false
        state: present
        networks:
        - name: "{{ nic1_network }}"
          device_type: vmxnet3
        - name: "{{ nic2_network }}"
          device_type:  vmxnet3
      register: vm_net_reconfigured
