---
- hosts: all
  
  tasks:
      
    - name: Add Vlans
        
      shell : "nmcli con add type vlan con-name vlan{{ item }} dev {{ interface_id }} id {{ item }}"
      with_items: "{{ vlan_id }}"
      
      register: create_output 
    - debug:
        var : "create_output.stdout"
       
        
    - name: List Network Configuration
      shell : "nmcli con show"
      register: show_output
    - debug:
        var : "show_output.stdout.split('\n')"
        
    
