---
- hosts: all
  
  tasks:
   # - name: Print
    - debug:
        var : "vlan_id"
    #    var : "vlan_id.0"
    #    var : "vlan_id.1"
        
    - name: Add Vlans
      shell : "nmcli con add type vlan con-name vlan{{ vlan_id.item }} dev {{ interface_id }} id {{ vlan_id.item }}"
      with_items: 
        - vlan_id.0
        - vlan_id.1
      register: create_output 
    - debug:
        var : "create_output.stdout"
       
        
    - name: List Network Configuration
      shell : "nmcli con show"
      register: show_output
    - debug:
        var : "show_output.stdout.split('\n')"
        
    
